version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_game_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: game 
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  game-app:
    build: .
    command: ["/app/docker/app.sh"]
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy