"""empty message

Revision ID: 142103f8aa3d
Revises: d704491807ea
Create Date: 2024-05-23 16:48:51.695318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142103f8aa3d'
down_revision: Union[str, None] = 'd704491807ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms_users', 'current_cell',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms_users', 'current_cell',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
