"""empty message

Revision ID: a527ab7d0ece
Revises: 142103f8aa3d
Create Date: 2024-05-24 18:10:34.355920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a527ab7d0ece'
down_revision: Union[str, None] = '142103f8aa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('players_total', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'players_total')
    # ### end Alembic commands ###
